id: P19217DE8
initial_creation_type: ocr
source_metadata:
  volumes:
    5d53743812f34b3485ca35c76464bed1:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: རྡོ་རྗེ་བདེ་རྒྱས་དབྱངས་ཅན་མའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
